locale = "id-ID"
label = "Indonesia"
weight = 1
title = "North7"

[params]
displayName = "ID"
isoCode = "id"
rtl = false
description = "Blog hobi yang menulis tentang games, Linux, networking, dan anime"
dateFormat = ":date_long"
copyright = "Copyright 2024 — North7. All rights reserved."

  [params.author]
  name = "North7"
  image = "img/avatar.png"
  headline = "Blog hobi: games, Linux, networking, dan anime"
  bio = "Artikel, ulasan, dan tutorial seputar hobi favorit"

    [[params.author.links]]
    facebook = "#"

    [[params.author.links]]
    youtube = "#"
