locale = "id-ID"
label = "Indonesia"
weight = 1
title = "North7 - Ngulik Linux, Networking & Teknologi"

[params]
displayName = "ID"
isoCode = "id"
rtl = false
description = "Ngulik Linux, networking, open source, dan teknologi dari hal sederhana sampai yang bikin penasaran, lengkap dengan tutorial, panduan, tips, dan berita terbaru."
dateFormat = ":date_long"
copyright = "Copyright 2026 - North7. All rights reserved."

  [params.author]
  name = "North7"
  image = "img/logo.png"
  headline = "Media Linux, Networking, dan update teknologi"
  bio = "Artikel, ulasan, dan tutorial Linux serta teknologi terkini"

    [[params.author.links]]
    facebook = "#"

    [[params.author.links]]
    youtube = "#"
